/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 30;
  /** RegularExpression Id. */
  int POSDIGIT = 31;
  /** RegularExpression Id. */
  int ZERO = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int IDENT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"print\"",
    "\"return\"",
    "\"while\"",
    "\"if\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"else\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 28>",
    "<token of kind 29>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
